language: go
go:
  - 1.6
env:
  - APPENGINE_VERSION=1.9.40 PROJECT_ID="george-moura-site" APPLICATION_CREDENTIALS="$(pwd)/service-account.json"
before_install:
- openssl aes-256-cbc -K $encrypted_0e2ffed888ec_key -iv $encrypted_0e2ffed888ec_iv -in service-account.json.enc -out service-account.json -d
- ./scripts/configure_gcloud.sh
- ./scripts/install_go_appengine.sh
install:
- go get -v -t -d google.golang.org/appengine/..
- ./scripts/get_dependencies.sh
script:
- go version
- ./scripts/run_tests.sh
deploy:
  provider: script
  script: scripts/deploy.sh
  on: master
