language: go
go:
  - 1.6
env:
  - APPENGINE_VERSION=1.9.40 PROJECT_ID="george-moura-site" APPLICATION_CREDENTIALS="$(pwd)/service-account.json"
before_install:
- openssl aes-256-cbc -K $encrypted_0e2ffed888ec_key -iv $encrypted_0e2ffed888ec_iv -in service-account.json.enc -out service-account.json -d
- sleep 5
- ./scripts/configure_gcloud.sh
- ./scripts/install_go_appengine.sh
- export GO_APPENGINE="$(pwd)/go_appengine"
- export APPENGINE_DEV_APPSERVER=$(pwd)/go_appengine/dev_appserver.py
install:
- go get -v -t -d google.golang.org/appengine/...
- ./scripts/get_dependencies.sh
script:
- go version
- go test -v google.golang.org/appengine/...
- go test -v -race google.golang.org/appengine/...
- $GO_APPENGINE/goapp test -race -v ./...
deploy:
  provider: script
  script: scripts/deploy.sh
  on: master
