application: george-moura-site
version: site2
runtime: php55
api_version: 1

handlers:
- url: /css
  static_dir: public_html/css

- url: /(.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg))$
  static_files: georgesite/\1
  upload: georgesite/.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg)$
  application_readable: true

- url: /.*
  script: public_html/index.php

skip_files:
- ^(.*/)?\.zip$
- ^(.*/)?\.bat$
- ^(.*/)?\.sh$
- ^(.*/)?\.md$
- georgesite/wp-content/uploads/
- georgesite/wp-content/cache/autoptimize/
- georgesite/wp-content/themes/georgetheme/
- georgesite/wp-content/themes/spine/
- georgesite/wp-content/themes/twentyeleven/
- georgesite/wp-content/themes/twentyfourteen/
- georgesite/wp-content/themes/twentyten/
- georgesite/wp-content/themes/twentytwelve/
- georgesite/wp-content/themes/wp-polymer-theme/
- .git