application: george-moura-site
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app
- url: /css
  static_dir: public/css/
- url: /images
  static_dir: public/images/
- url: /wp-includes
  static_dir: public/wp-includes/images/smiles