application: george-moura-site
version: 20160707t1949
runtime: go
api_version: go1

default_expiration: "30m"

handlers:

- url: /css
  static_dir: public/css/

- url: /js
  static_dir: public/js/

- url: /font
  static_dir: public/font/

- url: /images
  static_dir: public/images/

- url: /wp-includes/images/smilies/
  static_dir: public/wp-includes/images/smilies

- url: /(.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg))$
  static_files: public/images\1
  upload: public/images/.*\.(ico|jpg|jpeg|png|gif|woff|ttf|otf|eot|svg)$
  application_readable: true

- url: /robots.txt
  script: public/robots.txt

- url: /.*
  script: _go_app
  secure: always
